### ISSUE TITLE
Confusion with 'Streaming Application Developer Guide'

### ISSUE THREAD

**Issue by Renkai** [gearpump/gearpump.github.io#17]
In the implement of 
https://github.com/gearpump/gearpump.github.io/blob/master/docs/0.6/how_to_write_a_streaming_application.md#split-processor
`import taskContext.{output, self}` imported `self`.
If I do not import it,it seems the logic is excatly the same.
Is there any other consideration about this import?

**Comment by manuzhang** [comment]
That is no longer needed. We should've removed it.
