### ISSUE TITLE
Separate user guide into a set of documents

### ISSUE THREAD

**Issue by whjiang** [gearpump/gearpump.github.io#24]
I think we can separate user guide into following documents:
1. Get Started
3. Developer Guide (including streaming, non-streaming, IDE, Concepts)
4. REST API Guide
5. Admin Guide (including command line syntax, configuration, HA)
6. Gearpump Internals (including at least delivery)
7. FAQ

**Comment by kkasravi** [comment]
I was looking at this [framework](https://github.com/ottogroup/SPQR) which is interesting. They also included a tutorials section. Should we also have something similar or would that be under developers guide?

**Comment by whjiang** [comment]
I am thinking about a general doc structure instead of breaking down existing userguide.md. How about this structure:
1. Get Started
2. Gearpump Introduction
   1. Gearpump Use Cases
      1. Gearpump UI with example
   2. Gearpump Unique Features
      1. Storm compatibility
         1. Dynamic DAG and live update
         2. IoT support
         3. 100% Akka 
3. Developer Guide
   1. Tutorial
      1. Preparation (Maven, IDE)
      2. Streaming App, WordCount (java & scala, DSL)
      3. Streaming App explanation and Concepts
      4. Non-Streaming App, DistributedShell
   2. API Doc
   3. REST API Doc
   4. Gearpump Internals (event processing, at least once delivery, transaction)
4. Admin Guide
   1. Deployment guide (command line, HA)
   2. Configuration guide
   3. performance tuning guide
5. Integration Guide
   1. Gearpump connectors (Kafka, HBase)
      1. How to use existing connectors
      2. Basic concepts of connectors
      3. How to develop new connectors
   2. Migration Guide
      1. Run Storm application on Gearpump
      2. Run Samoa application on Gearpump
   3. Gearpump with other frameworks
      1. use Spark to train ML model and use Gearpump to run it. 
6. FAQ

**Comment by kkasravi** [comment]
@whjiang I like this structure. Possible improvements

> 1. Connectors like kafka, hbase should perhaps be in the tutorial section as well. 
> 2. Should we be mentioning dynamic dag capabilities anywhere in the tutorial or developer section?

**Comment by whjiang** [comment]
@kkasravi 
1. we definitely can mention about Kafka/HBase connectors in tutorial. But, they are part of an example instead of a standalone page. I prefer to have tutorial example based. 
2. Sure. we can mention about this feature briefly in tutorial if we have a good example for this feature. And we definitely need a subsection in developer to tell how to program this feature. 

I will prefer to have all these section and subsection as standalone pages. But, not sure whether it is possible or not for mkdocs. 

And I am thinking about rename "dynamic DAG" to some more intuitive name, e.g. "live update"?

**Comment by kkasravi** [comment]
The [SPQR](http://data-artisans.com/how-we-selected-apache-flink-at-otto-group/) framework uses **Hot Deployment & Pipeline Redeployment/Reconfiguration During Runtime**

**Comment by whjiang** [comment]
@kkasravi so long a name. Better a shorter name.

**Comment by kkasravi** [comment]
@whjiang - yes this was only an example. How bout **ambulant topologies**

**Comment by whjiang** [comment]
kkasravi commented 12 hours ago
@whjiang - yes this was only an example. How bout ambulant topologies

I mistook it as **ambulant technology**.

**Comment by clockfly** [comment]
+1

**Comment by manuzhang** [comment]
Could we have a column for "Blogs" ?

**Comment by whjiang** [comment]
OK for "blogs".

**Comment by stanleyxu2005** [comment]
+1 and consider make README.md simpler.
