### ISSUE TITLE
Use Jekyll instead of Mkdocs for Gearpump Documentation

### ISSUE THREAD

**Issue by whjiang** [gearpump/gearpump.github.io#25]
It seems Jekyll (http://jekyllrb.com/) is documentation tool. Flink, Spark and other projects all using this tool for documentation. And it supports functionality like codetabs (demo code for different languages in tabs). 

Take Flink as an example, it uses following tools for documentaton:
1. Jekyll for general document generator. it can accept multiple languages as input.
2. kramdown is used to support Github favored Markdown as input language.
3. Pygments is used to support code syntax highlight.

I suggest we migrate to Jeykll as part of #24 restructure activity.

**Comment by stanleyxu2005** [comment]
+1

**Comment by whjiang** [comment]
done via branch doc_reorg
