### ISSUE TITLE
Gearpump Doc Reorg Remaining tasks

### ISSUE THREAD

**Issue by whjiang** [gearpump/gearpump.github.io#30]
Remaining task list:
- [x] Rewrite gearpump.io web pages to make it more attractive. Content shall not totally overlap/copy of  Gearpump docs. (owner: Kam)
- [x] Rewrite style (CSS) for gearpump.io. (owner: Kam)
- [ ] Adding more pages

**Comment by clockfly** [comment]
doc link is broken
http://www.gearpump.io/releases/0.6.2-SNAPSHOT/index.html

**Comment by clockfly** [comment]
Another problem is that now the website is not compatible with mobile device.

**Comment by clockfly** [comment]
@kkasravi 
Sorry, I reverted your two PR.

There are several pieces missing.
1. there is no user guide. 
User guide is the major part of the documentation. Looks like now it is moved to another repo. I think there should be two part for each release. One is user guide, the other is API reference doc.
https://github.com/gearpump/gearpump/tree/docs/docs
1. It looks surperising to me what the doc source code can even work. I don't know how _site sub-folder is get rendered.

**Comment by clockfly** [comment]
Looks like we are using github built-in Jekyll, do we need _site/ at all?

**Comment by clockfly** [comment]
_site is not needed, I removed it.

**Comment by clockfly** [comment]
Here is the right steps:
1. goto https://github.com/gearpump/gearpump/tree/docs, merge it into master.
2. follow guide of https://github.com/gearpump/gearpump.github.io/tree/master/releases
  a. run docs/build_doc.sh in gearpump/docs
  b. copy it into releases/

**Comment by kkasravi** [comment]
@clockfly Does this mean that both sites (gearpump, gearpump.io) are now incompatible with mobile? I copied what was under gearpump/gearpump/docs/{css,js}

**Comment by stanleyxu2005** [comment]
@kkasravi The reason might be I've changed the default page width to 960px in `gearpump/docs/css/main.css` 

```
.container {
max-width:960px
}
```

**Comment by kkasravi** [comment]
@clockfly @whjiang I think we should have gearpump.io updated automatically as part of travis when we release. Perhaps as new issue opened under gearpump repo.

**Comment by kkasravi** [comment]
@stanleyxu2005 can we do min, max width's ?

**Comment by kkasravi** [comment]
@clockfly @whjiang @stanleyxu2005 I don't think we should have SNAPSHOT's under gearpump.io. I had set GEARPUMP_VERSION to a SNAPSHOT just to get things working and for testing. I thought we would 
1. Release 0.6.2
2. Update gearpump.io

**Comment by whjiang** [comment]
@kkasravi @clockfly @stanleyxu2005 My original plan is to merge Gearpump/docs to Gearpump master branch first and then update Gearpump.io website. But as Gearpump.io website has been updated first, let's 
1. merge Gearpump docs branch to Gearpump master
2. make a document build and put it under Gearpump.io releases directory to fix the website temporrarly. 
3. when Gearpump make next release, upload the release doc again to Gearpump.io releases directory to make it formal available.
