### ISSUE TITLE
Only overview page is displayed on mobile 

### ISSUE THREAD

**Issue by manuzhang** [gearpump/gearpump.github.io#51]
Here is a screenshot from my Android Chrome. Only overview page but **no other tabs on the navigation bar**. 
![screenshot_2016-01-07-12-04-45_com android chrome](https://cloud.githubusercontent.com/assets/1191767/12162017/9f76e8be-b537-11e5-816e-14b9dbcee7a9.png)

**Comment by manuzhang** [comment]
fixed in bd0384930aa2fad6fa57e4e3657eff12c0d5304d

**Comment by clockfly** [comment]
![different](https://cloud.githubusercontent.com/assets/2595532/12346324/704aada2-bb8e-11e5-9734-666385634fb1.png)

**Comment by clockfly** [comment]
There are two styles for the dropdown.
